import React, { CSSProperties } from 'react';
import {
  AccessibilityNewRounded,
  AccountBalanceRounded,
  AddCircleRounded,
  AlarmOnRounded,
  AssignmentIndRounded,
  BlockRounded,
  BookRounded,
  BorderColorRounded,
  BugReportRounded,
  BusinessCenterRounded,
  CakeRounded,
  ChevronLeftRounded,
  ChevronRightRounded,
  ChildCareRounded,
  CloseRounded,
  CloudRounded,
  DeleteOutlineRounded,
  DeleteRounded,
  DirectionsCarRounded,
  DoneRounded,
  EditRounded,
  EmailRounded,
  EmojiObjectsRounded,
  ErrorRounded,
  ExitToAppRounded,
  ExpandLessRounded,
  ExpandMoreRounded,
  ExtensionRounded,
  FavoriteRounded,
  FileCopyOutlined,
  FindInPageRounded,
  GavelRounded,
  GetAppRounded,
  HomeRounded,
  HourglassEmptyRounded,
  HowToRegRounded,
  LanguageRounded,
  Link,
  LinkOff,
  LocationCityRounded,
  LockOpenRounded,
  LockRounded,
  LoopRounded,
  MailRounded,
  MapRounded,
  MoreHorizRounded,
  MoreVertRounded,
  PersonAddRounded,
  PersonRounded,
  PhoneRounded,
  PlaylistAddCheckRounded,
  PlaylistPlayRounded,
  PowerSettingsNewRounded,
  PublishRounded,
  QuestionAnswerRounded,
  RedoRounded,
  RemoveCircleRounded,
  ReportProblemRounded,
  RestorePageRounded,
  RoomRounded,
  SearchRounded,
  SendRounded,
  SettingsEthernetRounded,
  SettingsRounded,
  StoreRounded,
  SubdirectoryArrowRightRounded,
  SupervisorAccountRounded,
  UndoRounded,
  UpdateRounded,
  VisibilityRounded,
  VpnKeyRounded,
} from '@material-ui/icons';
import { categoryIconNameType } from '@label/core';
import { Tooltip } from './Tooltip';

export { Icon };

export type { iconNameType };

const materialIconMapping = {
  addPerson: PersonAddRounded,
  admin: SupervisorAccountRounded,
  arrowDown: ExpandMoreRounded,
  arrowLeft: ChevronLeftRounded,
  arrowRight: ChevronRightRounded,
  arrowUp: ExpandLessRounded,
  assigned: HowToRegRounded,
  assignment: AssignmentIndRounded,
  bug: BugReportRounded,
  check: DoneRounded,
  clock: AlarmOnRounded,
  close: CloseRounded,
  copy: FileCopyOutlined,
  delete: DeleteRounded,
  deleteOutline: DeleteOutlineRounded,
  discussion: QuestionAnswerRounded,
  doubleArrow: SettingsEthernetRounded,
  edit: EditRounded,
  edited: BorderColorRounded,
  error: ErrorRounded,
  eye: VisibilityRounded,
  export: GetAppRounded,
  find: FindInPageRounded,
  home: HomeRounded,
  human: AccessibilityNewRounded,
  key: VpnKeyRounded,
  lightBulb: EmojiObjectsRounded,
  link: Link,
  lock: LockRounded,
  login: ExitToAppRounded,
  logout: PowerSettingsNewRounded,
  mail: MailRounded,
  minus: RemoveCircleRounded,
  moreHoriz: MoreHorizRounded,
  moreVert: MoreVertRounded,
  playlistPlay: PlaylistPlayRounded,
  playlistCheck: PlaylistAddCheckRounded,
  plus: AddCircleRounded,
  publish: PublishRounded,
  puzzle: ExtensionRounded,
  redo: RedoRounded,
  restore: RestorePageRounded,
  reset: LoopRounded,
  search: SearchRounded,
  send: SendRounded,
  settings: SettingsRounded,
  stop: BlockRounded,
  turnRight: SubdirectoryArrowRightRounded,
  undo: UndoRounded,
  unlink: LinkOff,
  unlock: LockOpenRounded,
  update: UpdateRounded,
  waiting: HourglassEmptyRounded,
  warning: ReportProblemRounded,
};

const categoryIconMapping: Record<categoryIconNameType, React.ElementType> = {
  bank: AccountBalanceRounded,
  book: BookRounded,
  cake: CakeRounded,
  car: DirectionsCarRounded,
  city: LocationCityRounded,
  child: ChildCareRounded,
  cloud: CloudRounded,
  email: EmailRounded,
  forbidden: BlockRounded,
  hammer: GavelRounded,
  heart: FavoriteRounded,
  location: RoomRounded,
  map: MapRounded,
  pencil: EditRounded,
  person: PersonRounded,
  phone: PhoneRounded,
  store: StoreRounded,
  web: LanguageRounded,
  work: BusinessCenterRounded,
};

const iconMapping = {
  ...materialIconMapping,
  ...categoryIconMapping,
};

type iconNameType = keyof typeof materialIconMapping | keyof typeof categoryIconMapping;

function Icon(props: { iconName: iconNameType; hint?: string; style?: CSSProperties }) {
  const IconComponent = iconMapping[props.iconName];
  if (props.hint) {
    return (
      <Tooltip title={props.hint}>
        <IconComponent style={props.style} />
      </Tooltip>
    );
  }
  return <IconComponent style={props.style} />;
}
