version: "3.7"

services:
  backend:
    build:
      context: ../../
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo:4.4
    volumes:
      - mongo-storage:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  mongo-storage:
    driver: local
