image: docker:20.10.22
services:
  - docker:20.10.22-dind

variables:
  docker_backend_image: '$CI_REGISTRY/cour-de-cassation/label/backend:$CI_COMMIT_SHORT_SHA'
  docker_client_image: '$CI_REGISTRY/cour-de-cassation/label/client:$CI_COMMIT_SHORT_SHA'

stages:
  - build_back
  - deploy_back
  - build_front
  - deploy_front

build_and_push_label_backend:
  stage: build_back
  variables:
    HTTP_PROXY: $HTTP_PROXY_DEV
    HTTPS_PROXY: $HTTPS_PROXY_DEV
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

    # To avoid rebuild existing image when adding tag to a commit
    - |
      if docker pull "$docker_backend_image"; then
        echo "Docker image $docker_backend_image already exist, skiping build and push."
        exit 0
      fi

    - docker build
      --build-arg http_proxy=$HTTP_PROXY
      --build-arg https_proxy=$HTTPS_PROXY
      --target label-backend
      -f Dockerfile.label-backend
      -t $docker_backend_image .
    - docker push $docker_backend_image
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "cicd-refacto"'
    - if: '$CI_COMMIT_TAG'
  tags:
    - docker

build_and_push_label_client:
  stage: build_front
  variables:
    HTTP_PROXY: $HTTP_PROXY_DEV
    HTTPS_PROXY: $HTTPS_PROXY_DEV
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - export NODE_OPTIONS=--openssl-legacy-provider # utile ?

    # To avoid rebuild existing image when adding tag to a commit
    - |
      if docker pull "$docker_client_image"; then
        echo "Docker image $docker_client_image already exist, skiping build and push."
        exit 0
      fi

    - docker build
      --build-arg http_proxy=$HTTP_PROXY
      --build-arg https_proxy=$HTTPS_PROXY
      --target label-client
      -f Dockerfile.label-client
      -t $docker_client_image .
    - docker push $docker_client_image
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "cicd-refacto"'
    - if: '$CI_COMMIT_TAG'
  tags:
    - docker

.backend_deploy_template:
  stage: deploy_back
  environment: $ENV
  image: alpine/ansible:2.16.1
  script:
    - mkdir /root/.ssh
    - cat $SSH_KEY > /root/.ssh/id_rsa
    - cat $KNOWN_HOSTS > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/known_hosts
    - ansible-playbook -e label_backend_image=$docker_backend_image -i ansible/inventories/$ENV.yml ansible/deploy_label_backend.yml --vault-password-file=$ANSIBLE_VAULT_PASS
  tags:
    - docker

.client_deploy_template:
  stage: deploy_front
  environment: $ENV
  image: alpine/ansible:2.16.1
  script:
    - mkdir /root/.ssh
    - cat $SSH_KEY > /root/.ssh/id_rsa
    - cat $KNOWN_HOSTS > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/known_hosts
    - ansible-playbook -e label_client_image=$docker_client_image -i ansible/inventories/$ENV.yml ansible/deploy_label_client.yml --vault-password-file=$ANSIBLE_VAULT_PASS
  tags:
    - docker

deploy_dev_backend:
  variables:
    ENV: dev
  extends: .backend_deploy_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "cicd-refacto"'
      when: on_success
  needs:
    - build_and_push_label_backend

deploy_preprod_backend:
  variables:
    ENV: preprod
  extends: .backend_deploy_template
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs:
    - deploy_dev_backend

deploy_prod_backend:
  variables:
    ENV: prod
  extends: .backend_deploy_template
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs:
    - deploy_preprod_backend


deploy_dev_client:
  variables:
    ENV: dev
  extends: .client_deploy_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "cicd-refacto"'
      when: on_success
  needs:
    - build_and_push_label_client

deploy_preprod_client:
  variables:
    ENV: preprod
  extends: .client_deploy_template
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs:
    - deploy_dev_client

deploy_prod_client:
  variables:
    ENV: prod
  extends: .client_deploy_template
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs:
    - deploy_preprod_client

