version: '3.7'

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431
  backend:
    build:
      context: ./
      dockerfile: DockerfilePreProd
    environment:
      - RUN_MODE=PREPROD
      - SENDGRID_API_KEY=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
#    image: label-image
    ports:
      - 55430:55430
      - 55432:55432
    depends_on:
      - labelDb

networks:
  default:
    name: label-network

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
