version: "3.7"

services:
  backend:
    build:
      context: ./
      dockerfile: DockerfileBackend
    environment:
      - RUN_MODE=LOCAL
      - SENDGRID_API_KEY=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
      - WEBAPP_URL=http://localhost:7505
    ports:
      - "7505:7505"
    depends_on:
      - db
  db:
    image: mongo:4.4
    volumes:
      - mongo-storage:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  mongo-storage:
    driver: local
