name: label

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431

  backend:
    build:
      context: ./
      dockerfile: DockerfileLocalDev
    environment:
      - RUN_MODE=LOCAL
    ports:
      - "55430:55430"
    depends_on:
      - labelDb
    env_file:
      - docker.env
    volumes:
      - sso_files:/usr/src/app/sso_files
    networks:
      - default
      - dbsder-external-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
  dbsder-external-network:
    #external: true

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
  sso_files:
    driver: local
