version: '3.7'

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431
    networks:
      label-network:
        ipv4_address: 10.5.0.5
  backend:
    build:
      context: ./
      dockerfile: DockerfileProd
    environment:
      - RUN_MODE=LOCAL
      - SENDGRID_API_KEY=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
      - WEBAPP_URL=http://localhost:55432
    image: label-prod
    ports:
      - 55430:55430
      - 55432:55432
    networks:
      label-network:
        ipv4_address: 10.5.0.6  
    depends_on:
      - labelDb

networks:
  label-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
