version: '3.7'

services:
  backend:
    build:
      context: ./
      dockerfile: DockerfileLocal
    environment:
      - RUN_MODE=LOCAL
      - SENDGRID_API_KEY=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
      - WEBAPP_URL=http://localhost:8091
    ports:
      - '8091:8091'
    depends_on:
      - labelDb
  labelDb:
    image: mongo:4.4
    command: mongod --port 27023
    volumes:
      - mongo-storage:/data/db
    expose:
      - 27023
    ports:
      - 27023:27023

volumes:
  mongo-storage:
    driver: local
