version: "3.7"

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431
  backend:
    build:
      context: ./
      dockerfile: DockerfileLocalDev
    environment:
      - RUN_MODE=LOCAL
    #    image: label-image
    ports:
      - "55430:55430"
    depends_on:
      - labelDb
    networks:
      - default
      - dbsder-external-network

networks:
  default:
    name: label-network
  dbsder-external-network:
    external: true

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
