name: label

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.label.local
    ports:
      - "55430:55430"
    depends_on:
      - labelDb
    environment:
      - RUN_MODE=LOCAL
    env_file:
      - .env
    volumes:
      - .:/home/node
  client:
    build:
      context: ./
      dockerfile: Dockerfile.label.local
    ports:
      - "55432:55432"
    depends_on:
      - labelDb
    environment:
      - RUN_MODE=LOCAL
    env_file:
      - .env
    volumes:
      - .:/home/node
    command: "yarn start:client:dev"
    stdin_open: true

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
