version: '3.7'

services:
  {dbName}:
    image: mongo:4.4
    command: mongod --port {dbPort}
    volumes:
      - mongo-storage:/data/db
    expose:
      - {dbPort}
    ports:
      - {dbPort}:{dbPort}
  backend:
    build:
      context: ./
      dockerfile: DockerfileLocal
    environment:
      - RUN_MODE=LOCAL
      - SENDGRID_API_KEY=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
#    image: label-image
    ports:
      - {serverPort}:{serverPort}
      - {clientPort}:{clientPort}
    depends_on:
      - {dbName}

networks:
  default:
    name: label-network

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
