---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-nlp-annotation
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/5 4-17 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-nlp-annotation
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/annotateDocumentsWithoutAnnotationsWithNlp.js -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
                - name: NODE_TLS_REJECT_UNAUTHORIZED
                  value: "0"
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-import-j-7
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/30 4-10 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-import-j-7
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/importAllDocumentsFromSderSince.js --days 7 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-urgent-import
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "0 8,10,12,14 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-urgent-import
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/autoImportDocumentsFromSder.js --count 500 --threshold 500 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-import-chained
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "0 17 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-import-chained
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/importChainedDocumentsFromSder.js --count 500 --threshold 500 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-export-j-4
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "30 17 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-export-j-4
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/exportTreatedDocumentsSince.js -e environments/prodEnvironment.json -s settings/settings.json --days 4
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-export-publishable
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "58 11 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-export-publishable
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/exportTreatedPublishableDocuments.js -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-free-pending
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/16 4-17 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-free-pending
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/freePendingDocuments.js --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-purge-m-6
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "0 19 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-purge-m-6
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/purgeDb.js --beforeMonths 6 --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-renew-cache
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/5 4-17 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-renew-cache
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/renewCache.js --beforeMinutes 5 --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
