---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-nlp-annotation
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/5 4-17 * * *"
  # support 288 successes, meaning 24h with no decision to handle = treatment of less than 5min
  successfulJobsHistoryLimit: 288
  # support 168 failure, meaning 168hours = 1 week if annotation is interrupted due to activeDeadlineSeconds = 1h
  failedJobsHistoryLimit: 168
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-nlp-annotation
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/annotateDocumentsWithoutAnnotationsWithNlp.js -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
                - name: NODE_TLS_REJECT_UNAUTHORIZED
                  value: "0"
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-import-j-7
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/30 4-10 * * *"
  # support 12 treatments a day, keeping failure and success for a full week, meaning 84 iterations
  successfulJobsHistoryLimit: 84
  failedJobsHistoryLimit: 84
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-import-j-7
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/importAllDocumentsFromSderSince.js --days 7 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-urgent-import
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "15 6-17 * * *"
  # support 12 treatments a day, keeping failure and success for a full week, meaning 84 iterations
  successfulJobsHistoryLimit: 84
  failedJobsHistoryLimit: 84
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 1800
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-urgent-import
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/autoImportDocumentsFromSder.js --count 500 --threshold 1000 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-import-chained
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "0 17 * * *"
  # supports one treatment per day, keeping logs for a full week
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-import-chained
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/importChainedDocumentsFromSder.js --count 500 --threshold 500 -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-export-j-4
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "30 17 * * *"
  # keeping logs for 7 days, once a day
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-export-j-4
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/exportTreatedDocumentsSince.js -e environments/prodEnvironment.json -s settings/settings.json --days 4
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-export-publishable
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "58 13 * * *"
  # keeping logs 7 days, once a day
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-export-publishable
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/exportTreatedPublishableDocuments.js -e environments/prodEnvironment.json -s settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-free-pending
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/16 4-17 * * *"
  # keeps only 24h for this minor job, meaning approx 50 jobs
  successfulJobsHistoryLimit: 50
  failedJobsHistoryLimit: 50
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-free-pending
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/freePendingDocuments.js --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-purge-m-6
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "0 19 * * *"
  # keeps logs 7 days, once a day
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-purge-m-6
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/purgeDb.js --beforeMonths 6 --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-renew-cache
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "*/5 4-17 * * *"
  # keeps logs 24h, minor and very frequent job
  successfulJobsHistoryLimit: 168
  failedJobsHistoryLimit: 168
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-renew-cache
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/renewCache.js --beforeMinutes 5 --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP_ID}-job-renew-cache
  namespace: ${KUBE_NAMESPACE}
spec:
  schedule: "30 19 * * *"
  # keeps logs 7 days, once a day
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: ${APP_ID}-job-cleanning
              image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
              volumeMounts:
                - name: ${APP_ID}-config
                  mountPath: /home/node/packages/courDeCassation/environments
                  readOnly: true
              command:
                - /bin/sh
              args:
                - -c
                - node dist/scripts/cleanDocuments.js --environment environments/prodEnvironment.json --settings settings/settings.json
              env:
                - name: RUN_MODE
                  value: PROD
                - name: SDER_DB_URL
                  value: ${MONGODB_URI}:${MONGODB_PORT}
          restartPolicy: Never
          volumes:
            - name: ${APP_ID}-config
              secret:
                secretName: ${APP_ID}-config
