---
- name: Creation de la ConfigMap du backend
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ label_back_app_id }}-config"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      data:
        GIT_BRANCH: "{{ git_branch }}"
        LABEL_API_PORT: "{{ label_api_port }}"
        APP_HOST: "{{ label_app_host }}"
        APP_GROUP: "{{ label_app_group }}"
        APP_ID: "{{ label_back_app_id }}"
        APP_KEYWORD: "{{ label_app_keyword }}"
        APP_SCHEME: "{{ label_app_scheme }}"
        APP_SELF_SIGNED: "{{ label_app_self_signed }}"
        APP_PORT: "{{ label_app_port }}"
        DOCKER_USERNAME: "{{ label_docker_username }}"
        DOCKER_TARGET: "{{ label_back_docker_target }}"
        KUBE_ZONE: "{{ label_kube_zone }}"
        KUBE_TYPE: "{{ label_kube_type }}"
        KUBE_NAMESPACE: "{{ label_kube_namespace }}"
        ROOT_PATH: "{{ label_back_root_path }}"
        START_TIMEOUT: "{{ label_start_timeout }}"
        KUBECONFIG: "{{ label_kubeconfig }}"
        NLP_PSEUDONYMISATION_API_URL: "{{ nlp_pseudonymisation_api_url }}"
        NLP_PSEUDONYMISATION_API_ENABLED: "{{ nlp_pseudonymisation_api_enabled }}"
        DBSDER_API_URL: "{{ dbsder_api_url }}"
        DBSDER_API_VERSION: "{{ dbsder_api_version }}"
        DBSDER_API_ENABLED: "{{ dbsder_api_enabled }}"
        LABEL_DB_NAME: "{{ label_db_name }}"
        LABEL_CLIENT_URL: "{{ label_client_url }}"
