---
- name: Creation de la ConfigMap du backend
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ label_back_app_id }}-config"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      data:
        GIT_BRANCH: "{{ git_branch }}"
        APP_ID: "{{ label_back_app_id }}"
        KUBE_NAMESPACE: "{{ label_kube_namespace }}"
        ROOT_PATH: "{{ label_back_root_path }}"
        DBSDER_API_URL: "{{ dbsder_api_url }}"
        DBSDER_API_VERSION: "{{ dbsder_api_version }}"
        LABEL_API_PORT: "{{ label_api_port }}"
        LABEL_DB_NAME: "{{ label_db_name }}"
        LABEL_CLIENT_URL: "{{ label_client_url }}"
