---
- name: Creation de la ConfigMap du backend
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ label_back_app_id }}-config"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      data:
        GIT_BRANCH: "{{ git_branch }}"
        APP_ID: "{{ label_back_app_id }}"
        KUBE_NAMESPACE: "{{ label_kube_namespace }}"
        ROOT_PATH: "{{ label_back_root_path }}"
        NLP_PSEUDONYMISATION_API_URL: "{{ nlp_pseudonymisation_api_url }}"
        NLP_PSEUDONYMISATION_API_ENABLED: "{{ nlp_pseudonymisation_api_enabled }}"
        DBSDER_API_URL: "{{ dbsder_api_url }}"
        DBSDER_API_VERSION: "{{ dbsder_api_version }}"
        LABEL_API_PORT: "{{ label_api_port }}"
        LABEL_DB_NAME: "{{ label_db_name }}"
        LABEL_CLIENT_URL: "{{ label_client_url }}"
        SSO_SP_ENTITY_ID: "{{ sso_sp_entity_id }}"
        SSO_SP_ASSERTION_CONSUMER_SERVICE_LOCATION: "{{ sso_sp_assertion_consumer_service_location }}"
        SSO_IDP_METADATA: "{{ sso_idp_metadata }}"
        SSO_IDP_SINGLE_SIGN_ON_SERVICE_LOCATION: "{{ sso_idp_single_sign_on_service_location }}"
        SSO_IDP_SINGLE_LOGOUT_SERVICE_LOCATION: "{{ sso_idp_single_logout_service_location }}"
        SSO_CERTIFICAT: "{{ sso_certificat }}"
        SSO_SP_PRIVATE_KEY: "{{ sso_sp_private_key }}"
        SSO_NAME_ID_FORMAT: "{{ sso_name_id_format }}"
        SSO_SIGNATURE_ALGORITHM: "{{ sso_signature_algorithm }}"
        SESSION_DURATION: "{{ session_duration }}"
        SSO_FRONT_SUCCESS_CONNEXION_ANNOTATOR_URL: "{{ sso_front_success_connexion_annotator_url }}"
        SSO_FRONT_SUCCESS_CONNEXION_ADMIN_SCRUTATOR_URL: "{{ sso_front_success_connexion_admin_scrutator_url }}"
        SSO_FRONT_SUCCESS_CONNEXION_PUBLICATOR_URL: "{{ sso_front_success_connexion_publicator_url }}"
        SSO_ATTRIBUTE_NAME: "{{ sso_attribute_name }}"
        SSO_ATTRIBUTE_FIRSTNAME: "{{ sso_attribute_firstname }}"
        SSO_ATTRIBUTE_FULLNAME: "{{ sso_attribute_fullname }}"
        SSO_ATTRIBUTE_MAIL: "{{ sso_attribute_mail }}"
        SSO_ATTRIBUTE_ROLE: "{{ sso_attribute_role }}"
        SSO_APP_NAME: "{{ sso_app_name }}"
        SSO_APP_ROLES: "{{ sso_app_roles }}"
