---
- name: Deploy cronjob
  k8s:
    state: present
    apply: true
    verify_ssl: true
    definition: "{{ lookup('template', 'cronjob.yml.j2') }}"
  vars:
    name: "{{ job.name }}"
    schedule: "{{ job.schedule }}"
    successful_jobs_history_limit: "{{ job.successful_jobs_history_limit }}"
    failed_jobs_history_limit: "{{ job.failed_jobs_history_limit }}"
    backoff_limit: "{{ job.backoff_limit }}"
    parallelism: "{{ job.parallelism }}"
    active_deadline_seconds: "{{ job.active_deadline_seconds }}"
    name: "{{ job.name }}"
    command: "{{ job.command }}"
...
