---
- name: Creation Deployment
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ label_back_app_id }}-deployment"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ label_back_app_id }}"
        template:
          metadata:
            labels:
              app: "{{ label_back_app_id }}"
          spec:
            initContainers:
              - name: "{{ rclone_app_id }}"
                image: rclone/rclone:latest
                command:
                  - /bin/sh
                args:
                  - -c
                  - |
                    rclone -v sync s3:{{ sso_bucket }} /sso_files
                envFrom:
                  - secretRef:
                      name: "{{ rclone_app_id }}-secret"
                volumeMounts:
                  - name: "{{ rclone_app_id }}-pvc-sso"
                    mountPath: /sso_files
            containers:
              - name: "{{ label_back_app_id }}"
                image: "{{ label_backend_image }}"
                ports:
                  - containerPort: 55430
                envFrom:
                  - configMapRef:
                      name: "{{ label_back_app_id }}-config"
                  - secretRef:
                      name: "{{ label_back_app_id }}-secret"
                volumeMounts:
                  - name: "{{ rclone_app_id }}-pvc-sso"
                    mountPath: /home/node/packages/courDeCassation/sso_files
            volumes:
              - name: "{{ rclone_app_id }}-pvc-sso"
                persistentVolumeClaim:
                  claimName: "{{ rclone_app_id }}-pvc-sso"
