---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route-keycloak
        namespace: "{{ label_kube_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`lbl.judilibre-prive.local`) && PathPrefix(`/`)
            kind: Rule
            services:
              - name: "keycloak"
                port: 8088 

# - name: Creation middleware
#   k8s:
#     apply: true
#     state: present
#     verify_ssl: true
#     definition:
#       apiVersion: traefik.containo.us/v1alpha1
#       kind: Middleware
#       metadata:
#         name: keycloak-rewrite
#         namespace: "{{ label_kube_namespace }}"
#       spec:
#         replacePathRegex:
#           regex: "^/auth(/|$)(.*)"
#           replacement: "/$2"



