---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route-keycloack
        namespace: "{{ label_kube_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`lbl.judilibre-prive.local`) && PathPrefix(`/auth`)
            kind: Rule
            services:
              - name: "keycloak"
                port: "keycloak"


# - name: Creation middleware
#   k8s:
#     apply: true
#     state: present
#     verify_ssl: true
#     definition:
#       apiVersion: traefik.containo.us/v1alpha1
#       kind: Middleware
#       metadata:
#         name: label-keycloak-stripprefix
#         namespace: "{{ label_kube_namespace }}"
#       spec:
#         replacePathRegex:
#           regex: /(/|$)(.*)
#           replacement: /$2


