---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route
        namespace: label
      spec:
        entryPoints:
          - web

        routes:
          - match: Host(`juritj.judilibre-prive.local`) && PathPrefix(`/label/api`)
            kind: Rule
            services:
              - name: label-backend-service
                port: label-backend-port

---
- name: Creation middleware
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: label-backend-stripprefix
        namespace: label
      spec:
        replacePathRegex:
          regex: /label-backend(/|$)(.*)
          replacement: /$2


