---
- name: Creation Service
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ label_back_app_id }}-service"
        namespace: "{{ label_kube_namespace }}"
      spec:
        selector:
          app: "{{ label_back_app_id }}"
        ports:
          - name: label-backend-port
            port: "{{ label_back_port }}"
            targetPort: "{{ label_back_port }}"
        type: ClusterIP
