version: '3.7'

services:
  backend:
    build:
      context: ./
      dockerfile: DockerfileProd
    environment:
      - RUN_MODE=LOCAL
      - SENDGRID_API_KEY=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
      - WEBAPP_URL=http://localhost:{serverPort}
    ports:
      - '{serverPort}:{serverPort}'
    depends_on:
      - {dbName}
  {dbName}:
    image: mongo:4.4
    command: mongod --port {dbPort}
    volumes:
      - mongo-storage:/data/db
    expose:
      - {dbPort}
    ports:
      - {dbPort}:{dbPort}

volumes:
  mongo-storage:
    driver: local
