---
jobs:
  - name: "nlp-annotation"
    schedule: "*/5 2-20 * * *"
    successful_jobs_history_limit: 288
    failed_jobs_history_limit: 134
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 3600
    command: "dist/scripts/annotateDocumentsWithoutAnnotationsWithNlp.js"
  - name: "import-j-7"
    schedule: "*/30 6-12 * * *"
    successful_jobs_history_limit: 84
    failed_jobs_history_limit: 84
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/importAllDocumentsFromSderSince.js --days 7"
  - name: "filler-import"
    schedule: "15 6-17 * * *"
    successful_jobs_history_limit: 84
    failed_jobs_history_limit: 84
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 1800
    command: "dist/scripts/autoImportDocumentsFromSder.js --count 500 --threshold 1000"
  - name: "import-chained"
    schedule: "0 17 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/importChainedDocumentsFromSder.js --count 500 --threshold 1500"
  - name: "export-j-4"
    schedule: "30 17 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/exportTreatedDocumentsSince.js --days 4"
  - name: "export-publishable"
    schedule: "50 13 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/exportTreatedPublishableDocuments.js"
  - name: "free-pending"
    schedule: "*/16 4-17 * * *"
    successful_jobs_history_limit: 50
    failed_jobs_history_limit: 50
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/freePendingDocuments.js"
  - name: "purge-m-6"
    schedule: "0 19 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 2
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/purgeDb.js --beforeMonths 6"
  - name: "renew-cache"
    schedule: "*/5 4-17 * * *"
    successful_jobs_history_limit: 168
    failed_jobs_history_limit: 168
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/renewCache.js --beforeMinutes 5"
  - name: "cleaning"
    schedule: "30 19 * * *"
    successful_jobs_history_limit: 7
    failed_jobs_history_limit: 7
    backoff_limit: 0
    parallelism: 1
    active_deadline_seconds: 300
    command: "dist/scripts/cleanDocuments.js"
