---
label_backend_namespace: label
label_backend_application: label-backend

jobs:
  nlp-annotation:
    name: "nlp-annotation"
    schedule: "*/5 2-20 * * *"
    successful_jobs_history_limit: "288"
    failed_jobs_history_limit: "134"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "3600"
    command: "dist/scripts/annotateDocumentsWithoutAnnotationsWithNlp.js"
  import_j_7:
    job_name: "import-j-7"
    job_schedule: "*/30 6-12 * * *"
    successful_jobs_history_limit: "84"
    failed_jobs_history_limit: "84"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/importAllDocumentsFromSderSince.js --days 7"
  filler_import:
    job_name: "filler-import"
    job_schedule: "15 6-17 * * *"
    successful_jobs_history_limit: "84"
    failed_jobs_history_limit: "84"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "1800"
    command: "dist/scripts/autoImportDocumentsFromSder.js --count 500 --threshold 1000"
  import_chained:
    job_name: "import-chained"
    job_schedule: "0 17 * * *"
    successful_jobs_history_limit: "7"
    failed_jobs_history_limit: "7"
    backoff_limit: "2"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/importChainedDocumentsFromSder.js --count 500 --threshold 1500"
  export_j_4:
    job_name: "export-j-4"
    job_schedule: "30 17 * * *"
    successful_jobs_history_limit: "7"
    failed_jobs_history_limit: "7"
    backoff_limit: "2"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/exportTreatedDocumentsSince.js"
  export_publishable:
    job_name: "export-publishable"
    job_schedule: "50 13 * * *"
    successful_jobs_history_limit: "7"
    failed_jobs_history_limit: "7"
    backoff_limit: "2"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/exportTreatedPublishableDocuments.js"
  free_pending:
    job_name: "free-pending"
    job_schedule: "*/16 4-17 * * *"
    successful_jobs_history_limit: "50"
    failed_jobs_history_limit: "50"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/freePendingDocuments.js"
  purge_m_6:
    job_name: "purge-m-6"
    job_schedule: "0 19 * * *"
    successful_jobs_history_limit: "7"
    failed_jobs_history_limit: "7"
    backoff_limit: "2"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: dist/scripts/purgeDb.js --beforeMonths 6"
  renew_cache:
    job_name: "renew-cache"
    job_schedule: "*/5 4-17 * * *"
    successful_jobs_history_limit: "168"
    failed_jobs_history_limit: "168"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/renewCache.js --beforeMinutes 5"
  cleaning:
    job_name: "cleaning"
    job_schedule: "30 19 * * *"
    successful_jobs_history_limit: "7"
    failed_jobs_history_limit: "7"
    backoff_limit: "0"
    parallelism: "1"
    active_deadline_seconds: "300"
    command: "dist/scripts/cleanDocuments.js"
  
# api_app_selector: api
# bucket_app_selector: bucket

# api_stripprefix: api-stripprefix
# bucket_stripprefix: bucket-stripprefix
