---
- name: Create rclone secret
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ rclone_app_id }}-secret"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ rclone_app_id }}"
      type: Opaque
      data:
        RCLONE_CONFIG_S3_TYPE: "{{ s3_type | b64encode }}"
        RCLONE_CONFIG_S3_PROVIDER: "{{ s3_provider | b64encode }}"
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ s3_access_key | b64encode }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ s3_secret_key | b64encode }}"
        RCLONE_CONFIG_S3_ENDPOINT: "{{ s3_endpoint | b64encode }}"
