---
- name: Creation secrets label backend
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: label-back-secret
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      type: Opaque
      data:
        SDER_DB_URL: "{{ '{{ vault_sder_mongodb_uri }}:{{ vault_sder_mongodb_port }}/{{ vault_sder_mongodb_name }}' | b64encode }}"
        MONGODB_URL: "{{ vault_label_mongodb_url | b64encode }}"

...
