# TODO : c'est commité sur github ça : on le vault ?

---
dev:
  children:
    k3s_master:
      hosts:
        k3s_master_host:
          ansible_host: 10.16.117.211
          ansible_ssh_private_key_file: ~/id_rsa
