version: "3.7"

services:
  preProdLabel:
    image: mongo:4.4
    command: mongod --port 27017
    volumes:
      - mongo-storage:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      label-network:
        ipv4_address: 10.5.0.5
  backend:
    build:
      context: ./
      dockerfile: DockerfilePreProdRpvj
    environment:
      - RUN_MODE=PREPROD
    #    image: label-image
    ports:
      - 55430:55430
      - 55432:55432
    networks:
      label-network:
        ipv4_address: 10.5.0.6
    depends_on:
      - preProdLabel

networks:
  label-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
