version: '3.7'

services:
  {dbName}:
    image: mongo:4.4
    command: mongod --port {dbPort}
    volumes:
      - mongo-storage:/data/db
    expose:
      - {dbPort}
    ports:
      - {dbPort}:{dbPort}
  backend:
    build:
      context: ./
      dockerfile: DockerfileLocalDev
    environment:
      - RUN_MODE=LOCAL
#    image: label-image
    ports:
      - '{serverPort}:{serverPort}'
    depends_on:
      - {dbName}

networks:
  default:
    name: label-network  

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
