---
- name: Creation de la ConfigMap du client
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ label_client_app_id }}-config"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_client_app_id }}"
      data:
        GIT_BRANCH: "{{ git_branch }}"
        APP_ID: "{{ label_client_app_id }}"
        KUBE_NAMESPACE: "{{ label_kube_namespace }}"
