---
- name: Creation Deployment
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ label_client_app_id }}-deployment"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_client_app_id }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ label_client_app_id }}"
        template:
          metadata:
            labels:
              app: "{{ label_client_app_id }}"
          spec:
            containers:
              - name: "{{ label_client_app_id }}"
                image: "{{ label_client_image }}"
                ports:
                  - containerPort: 55432
                envFrom:
                  - configMapRef:
                      name: "{{ label_client_app_id }}-config"
                  - secretRef:
                      name: "{{ label_client_app_id }}-secret"
                # livenessProbe:
                #   exec:
                #     command:
                #     - /bin/sh
                #     - -c
                #     - curl -s -k --fail --max-time 2 "http://localhost:55432/" | egrep -q 'true'
                #   initialDelaySeconds: 60
                #   periodSeconds: 15
                #   failureThreshold: 3
                #   timeoutSeconds: 5
                securityContext:
                  runAsUser: 1000
                  capabilities:
                    drop:
                      - all
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
