---
- name: Creation Ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route-client
        namespace: "{{ label_kube_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`lbl.judilibre-prive.local`) && PathPrefix(`/label`)
            kind: Rule
            services:
              - name: "{{ label_client_app_id }}-service"
                port: label-client-port
          # ajout
          - match: Host(`lbl.judilibre-prive.local`) && PathPrefix(`/label/api`)
            kind: Rule
            services:
              - name: "{{ label_back_app_id }}-service"
                port: label-backend-port

- name: Creation middleware
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: label-client-stripprefix
        namespace: label
      spec:
        replacePathRegex:
          regex: /label-client(/|$)(.*)
          replacement: /$2


