---
- name: Creation Ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route-client
        namespace: "{{ label_kube_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`lbl.judilibre-prive.local`) # && PathPrefix(`/label`)
            kind: Rule
            #middlewares:
            #  - name: label-client-stripprefix
            services:
              - name: "{{ label_client_app_id }}-service"
                port: label-client-port

- name: Creation middleware
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: label-client-stripprefix
        namespace: label
      spec:
        replacePathRegex:
          regex: /label(/|$)(.*)
          replacement: /$2


