---
- name: Creation secrets label client
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ label_client_app_id }}-secret"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_client_app_id }}"
      type: Opaque
      data:
        SDER_DB_URL: "{{ sder_mongodb_url | b64encode}}"
        MONGODB_URL: "{{ label_mongodb_url | b64encode }}"
        JWT_PRIVATE_KEY: "{{ jwt_private_key | b64encode}}"
