export { heights };

const heights = buildHeights();

function buildHeights() {
  const HEADER_HEIGHT = '72px';
  const ANNOTATOR_PANEL_HEADER_HEIGHT = '72px';
  const ANNOTATOR_PANEL_FOOTER_HEIGHT = '72px';
  const ANNOTATOR_PANEL_HEIGHT = `calc(100vh - ${HEADER_HEIGHT} - ${ANNOTATOR_PANEL_FOOTER_HEIGHT} - ${ANNOTATOR_PANEL_HEADER_HEIGHT})`;
  const ADMIN_PANEL_HEIGHT = `calc(100vh - ${HEADER_HEIGHT})`;
  const ADMIN_TREATMENTS_TABLE_HEADER_HEIGHT = '140px';
  const ADMIN_TREATMENTS_TABLE_HEIGHT = `calc(100vh - ${HEADER_HEIGHT} - ${ADMIN_TREATMENTS_TABLE_HEADER_HEIGHT})`;
  const SPECIAL_DOCUMENTS_TABLE_HEADER_HEIGHT = '72px';
  const SPECIAL_DOCUMENTS_TABLE_HEIGHT = `calc(100vh - ${HEADER_HEIGHT} - ${SPECIAL_DOCUMENTS_TABLE_HEADER_HEIGHT})`;
  const SPECIAL_DOCUMENTS_HEIGHT = `calc(100vh - ${HEADER_HEIGHT})`;
  const STATISTICS_HEADER_HEIGHT = '72px';
  const STATISTICS_BODY_HEIGHT = `calc(100vh - ${HEADER_HEIGHT} - ${STATISTICS_HEADER_HEIGHT})`;
  const ANONYMIZED_DOCUMENT_HEADER_HEIGHT = '72px';
  const ANONYMIZED_DOCUMENT_FOOTER_HEIGHT = '72px';
  const ANONYMIZED_DOCUMENT_HEIGHT = `calc(100vh - ${HEADER_HEIGHT} - ${ANONYMIZED_DOCUMENT_HEADER_HEIGHT} - ${ANONYMIZED_DOCUMENT_FOOTER_HEIGHT})`;

  return {
    header: HEADER_HEIGHT,
    annotatorPanelHeader: ANNOTATOR_PANEL_HEADER_HEIGHT,
    annotatorPanel: ANNOTATOR_PANEL_HEIGHT,
    annotatorPanelFooter: ANNOTATOR_PANEL_FOOTER_HEIGHT,
    anonymizedDocumentHeader: ANONYMIZED_DOCUMENT_HEADER_HEIGHT,
    anonymizedDocument: ANONYMIZED_DOCUMENT_HEIGHT,
    anonymizedDocumentFooter: ANONYMIZED_DOCUMENT_FOOTER_HEIGHT,
    adminPanel: ADMIN_PANEL_HEIGHT,
    adminTreatmentsTableHeader: ADMIN_TREATMENTS_TABLE_HEADER_HEIGHT,
    adminTreatmentsTable: ADMIN_TREATMENTS_TABLE_HEIGHT,
    specialDocuments: SPECIAL_DOCUMENTS_HEIGHT,
    specialDocumentsTableHeader: SPECIAL_DOCUMENTS_TABLE_HEADER_HEIGHT,
    specialDocumentsTable: SPECIAL_DOCUMENTS_TABLE_HEIGHT,
    statisticsHeaderHeight: STATISTICS_HEADER_HEIGHT,
    statisticsBodyHeight: STATISTICS_BODY_HEIGHT,
  };
}
