git_branch: dev

sder_mongodb_url: "{{ vault_sder_mongodb_url }}"
label_mongodb_url: "{{ vault_label_mongodb_url }}"
dbsder_api_key: "{{ vault_dbsder_api_key }}"
jwt_private_key: "{{ vault_jwt_private_key }}"
