---
- name: Creation Service
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: label-backend-service
        namespace: label
      spec:
        selector:
          app: label-backend
        ports:
          - name: label-backend-port
            port: 55430
            targetPort: 55430
        type: ClusterIP
