export { fr };

const fr = {
  annotationGuide: "Guide d'annotation",
  applyEveryWhere: 'Appliquer partout',
  askedAnnotations: 'Annotations demandées',
  associateTo: 'Associer à',
  cancel: 'Annuler',
  category: 'Catégorie',
  describeTheProblem: 'Décrivez le problème. Soyez exhaustif.',
  delete: 'Supprimer',
  email: 'E-mail',
  enterYourText: 'Saisissez votre texte...',
  forgottenPassword: 'Mot de passe oublié ?',
  login: 'Connexion',
  nOccurencesToObliterate: '{0} occurences à occulter',
  password: 'Mot de passe',
  passwordsMustBeIdentical: 'Les deux mots de passe doivent être identiques.',
  problemCategory: { bug: 'Bug', annotationProblem: "Problème lié à l'annotation", suggestion: 'Suggestion' },
  problemIsBlocking: `Ce problème m'empêche de terminer l'annotation du document.`,
  problemType: 'Type de problème',
  reportProblem: 'Signaler un problème',
  reset: 'Réinitialiser',
  saveDraft: 'Enregistrer le brouillon',
  send: 'Envoyer',
  validate: 'Valider',
};
