export { fr };

const fr = {
  applyEveryWhere: 'Appliquer à tous',
  askedAnnotations: 'Annotations demandées',
  associateTo: 'Associer à',
  cancel: 'Annuler',
  category: 'Catégorie',
  darkMode: 'Mode sombre',
  describeTheProblem: 'Décrivez le problème. Soyez exhaustif.',
  delete: 'Supprimer',
  displayMode: "Type d'affichage",
  email: 'E-mail',
  enterYourText: 'Saisissez votre texte...',
  forgottenPassword: 'Mot de passe oublié ?',
  lightMode: 'Mode lumineux',
  login: 'Connexion',
  logout: 'Déconnexion',
  originalText: 'Texte original',
  password: 'Mot de passe',
  passwordsMustBeIdentical: 'Les deux mots de passe doivent être identiques.',
  problemCategory: { bug: 'Bug', annotationProblem: "Problème lié à l'annotation", suggestion: 'Suggestion' },
  problemIsBlocking: `Ce problème m'empêche de terminer l'annotation du document.`,
  problemType: 'Type de problème',
  pseudonymisation: 'Pseudonymisation',
  redo: 'Rétablir',
  reportProblem: 'Signaler un problème',
  reset: 'Réinitialiser',
  resize: 'Redimensionner',
  saveDraft: 'Enregistrer le brouillon',
  send: 'Envoyer',
  settings: 'Réglages',
  undo: 'Annuler',
  unlink: 'Dissocier',
  validate: 'Valider',
};
