---
- name: Creation Deployment
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: label-backend-deployment
        namespace: label
        labels:
          app: 
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: label-backend
        template:
          metadata:
            labels:
              app: label-backend
          spec:
            containers:
              - name: label-backend
                image: "{{ label_backend_image }}"
                ports:
                  - containerPort: 55430
                envFrom:
                  - configMapRef:
                      name: "backend-config"
                  - secretRef:
                      name: "label-back-secret"
                # startupProbe:
                #   exec:
                #     command:
                #     - /bin/sh
                #     - -c
                #     - curl -s --fail --max-time 2 "http://localhost:55430/${ROOT_PATH}/health" | egrep -q 'true'
                #   initialDelaySeconds: 15
                #   periodSeconds: 5
                #   failureThreshold: 20
                # livenessProbe:
                #   exec:
                #     command:
                #     - /bin/sh
                #     - -c
                #     - curl -s --fail --retry-delay 0 --max-time 2 --retry 30 --retry-max-time 60 "http://localhost:55430/${ROOT_PATH}/health" | egrep -q 'true'
                #   initialDelaySeconds: 15
                #   periodSeconds: 15
                #   failureThreshold: 10
                #   timeoutSeconds: 60
                # securityContext:
                #   runAsUser: 1000
                #   capabilities:
                #     drop:
                #       - all
                #   allowPrivilegeEscalation: false
                #   readOnlyRootFilesystem: true
            #     volumeMounts:
            #       - name: label-backend-config
            #         mountPath: /home/node/packages/courDeCassation/environments
            #         readOnly: true
            # volumes:
            # - name: label-backend-config
            #   secret:
            #     secretName: label-backend-config
