---
- name: Render job template
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: "label-backend-job-{{job.value.name}}"
        namespace: label
      spec:
        schedule: "{{job.value.schedule}}"
        successfulJobsHistoryLimit: {{job.value.successful_jobs_history_limit | int}}
        failedJobsHistoryLimit: {{job.value.failed_jobs_history_limit | int}}
        concurrencyPolicy: Forbid
        jobTemplate:
          spec:
            backoffLimit: {{job.value.backoff_limit | int}}
            parallelism: {{job.value.parallelism | int}}
            template:
              spec:
                activeDeadlineSeconds: {{job.value.active_deadline_seconds | int}}
                containers:
                  - name: "label-backend-{{job.value.name}}"
                    image: "{{ label_backend_image }}"
                    # volumeMounts:
                    #   - name: label-backend-config
                    #     mountPath: /home/node/packages/courDeCassation/environments
                    #     readOnly: true
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - node {{ job.value.command }} -e environments/prodEnvironment.json -s settings/settings.json
                    envFrom:
                      - configMapRef:
                          name: "backend-config"
                      - secretRef:
                          name: "label-back-secret"
                restartPolicy: Never
                # volumes:
                #   - name: label-backend-config
                #     secret:
                #       secretName: label-backend-config
