---
- name: Render job template
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: label-backend-job-{{job_name}}
        namespace: label
      spec:
        schedule: "{{job_schedule}}"
        successfulJobsHistoryLimit: {{successful_jobs_history_limit}}
        failedJobsHistoryLimit: {{failed_jobs_history_limit}}
        concurrencyPolicy: Forbid
        jobTemplate:
          spec:
            backoffLimit: {{backoff_limit}}
            parallelism: ${{parallelism}}
            template:
              spec:
                activeDeadlineSeconds: {{active_deadline_seconds}}
                containers:
                  - name: label-backend-{{job_name}}
                    image: "{{ label_backend_image }}"
                    # volumeMounts:
                    #   - name: label-backend-config
                    #     mountPath: /home/node/packages/courDeCassation/environments
                    #     readOnly: true
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - node "{{ command }}" -e environments/prodEnvironment.json -s settings/settings.json
                    envFrom:
                      - configMapRef:
                          name: "backend-config"
                      - secretRef:
                          name: "label-back-secret"
                restartPolicy: Never
                # volumes:
                #   - name: label-backend-config
                #     secret:
                #       secretName: label-backend-config
