name: "🧪 Tests & ✨ Lint"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test Label
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build and Compile
        run: yarn compile

      - name: Run Tests
        run: yarn test

      - name: Run Lint
        run: yarn lint
